DROP TABLE IF EXISTS ROLE, CONTACT_DETAILS, USER, PATIENT, RESEARCH_PROJECT, AGREEMENT, LABORATORY_TEST_ORDER, TEST_RESULT, USER_ROLE, PATIENT_PROJECT;

CREATE TABLE IF NOT EXISTS ROLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role_type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTACT_DETAILS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(15) NOT NULL,
    UNIQUE(phone_number)
);

CREATE TABLE IF NOT EXISTS USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(80) NOT NULL,
    UNIQUE(username)
);

CREATE TABLE IF NOT EXISTS PATIENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    contact_details_id BIGINT,
    user_id BIGINT,
    CONSTRAINT FK_ContactPerson FOREIGN KEY (contact_details_id) REFERENCES CONTACT_DETAILS(id),
    CONSTRAINT FK_UserPatient FOREIGN KEY (user_id) REFERENCES USER(id)
);

CREATE TABLE IF NOT EXISTS RESEARCH_PROJECT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS AGREEMENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    CONSTRAINT FK_PatientAgreement FOREIGN KEY (patient_id) REFERENCES PATIENT(id),
    CONSTRAINT FK_ProjectAgreement FOREIGN KEY (project_id) REFERENCES RESEARCH_PROJECT(id)
);

CREATE TABLE IF NOT EXISTS LABORATORY_TEST_ORDER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    research_date DATETIME NOT NULL,
    patient_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    CONSTRAINT FK_PatientOrder FOREIGN KEY (patient_id) REFERENCES PATIENT(id),
    CONSTRAINT FK_ProjectOrder FOREIGN KEY (project_id) REFERENCES RESEARCH_PROJECT(id)
);

CREATE TABLE IF NOT EXISTS TEST_RESULT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    test_type VARCHAR(100) NOT NULL,
    result_description VARCHAR(500),
    order_id BIGINT NOT NULL,
    CONSTRAINT FK_OrderResult FOREIGN KEY (order_id) REFERENCES LABORATORY_TEST_ORDER(id)
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT FK_RoleUSERROLE FOREIGN KEY (role_id) REFERENCES ROLE(id),
    CONSTRAINT FK_UserUSERROLE FOREIGN KEY (user_id) REFERENCES USER(id)
);

CREATE TABLE IF NOT EXISTS PATIENT_PROJECT (
    patient_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    CONSTRAINT FK_PatientPATIENTPROJECT FOREIGN KEY (patient_id) REFERENCES PATIENT(id),
    CONSTRAINT FK_ProjectPATIENTPROJECT FOREIGN KEY (project_id) REFERENCES RESEARCH_PROJECT(id)
);